apiVersion: v1
kind: Pod
metadata:
  name: tiny-test
spec:
  containers:
    - name: tiny-test
      image: busybox:1.36
      command: ["sleep", "3600"]
      resources:
        requests:
          cpu: "100m"
          memory: "32Mi"
        limits:
          cpu: "200m"
          memory: "64Mi"
  restartPolicy: Never
